# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: true
dist: trusty
os:
  - linux
  # - osx
julia:
  - release
  # - nightly
notifications:
  email: false
branches:
  only: master
before_install:
  # install a newer version of CMake for LCMCore
  # - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz --no-check-certificate
  # - tar -xzf cmake-3.7.2-Linux-x86_64.tar.gz
  # - export PATH=`pwd`/cmake-3.7.2-Linux-x86_64/bin:$PATH

# uncomment the following lines to override the default test script
script:
  - julia -e 'Pkg.clone("https://github.com/rdeits/DrakeVisualizer.jl"); Pkg.checkout("DrakeVisualizer", "robocon2017"); Pkg.build("DrakeVisualizer")'
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Robocon2017Tutorial"); Pkg.test("Robocon2017Tutorial"; coverage=true)'
